### ISSUE TITLE
configparser.NoSectionError: No section: 'database'

### ISSUE THREAD

**Issue by JinwnK** [Wlab518/SV_procedure#2]
When I ran the pipeline in a docker container, an error occured like this:
```
(base) root@037af98a6c98:/opt/project# python /opt/conda/SV_procedure/call_SVs_procedure.py config.ini
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/configparser.py", line 848, in items
    d.update(self._sections[section])
KeyError: 'database'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/SV_procedure/call_SVs_procedure.py", line 643, in <module>
    main(args.ifile)
  File "/opt/conda/SV_procedure/call_SVs_procedure.py", line 39, in main
    checkmdb = con.items("database")[0][1]
  File "/opt/conda/lib/python3.10/configparser.py", line 851, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'database'
```
I tried the pipeline with the example data and the original config.ini file without changing.

**Comment by Wlab518** [comment]
To add the path of the "config.ini" file,  python /opt/conda/SV_procedure/call_SVs_procedure.py /opt/project/config.ini

**Comment by JinwnK** [comment]
It works.
Thank you for your fast reply.
